FROM node:22-alpine AS build

WORKDIR /app
ARG VITE_PROXY_HEADER
ENV VITE_PROXY_HEADER=$VITE_PROXY_HEADER

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
